# Lokal konfiqurasiya. .gitignore-dadır, commit olunmur.
voyanta:
  ai:
    api-key: AQ.Ab8RN6J42emQkBijEZqHXT-BF_-l1HnxWdwaAduUJ33208te9w
  oauth:
    google:
      client-id: 271303617766-v851cofvnc2t6qn2cee2minseps0h4pj.apps.googleusercontent.com